### ISSUE TITLE
Composer mediawiki/skin support

### ISSUE THREAD

**Issue by mwjames** [tinymighty/booty#8]
refs #6 

If you want to support `composer require ..` then you have to do some additional steps:
- Register your package with packagist.org (see https://packagist.org/packages/mediawiki/chameleon-skin or https://packagist.org/packages/mediawiki/vector-skin) in order for Composer to find the package
- The naming convention for the `mediawiki-skin` type is `name` + `-skin` (to distinguish it from a possible extension of the same name within the same `mediawiki/` namespace) so in your case `mediawiki/booty-skin`

```json
{
   "name"       : "mediawiki/booty-skin",
   "type"       : "mediawiki-skin",
   "description": "... skin",
   "keywords"   : [
       "wiki",
       "MediaWiki",
       "skin"
   ],
...
```
- For all global variables like (e.g. `wgExtensionCredits`) use `$GLOBALS` instead as in `$GLOBALS['wgExtensionCredits']`

**Comment by andru** [comment]
Thanks @mwjames I hope to get some time on this skin again soon, so I'll update it as per your advice at the next opportunity.

**Comment by andru** [comment]
I've made the changes you suggested @mwjames  and to my tests install via Composer now works as expected. 

I've got this package hosted at packagist under `tinymighty`, but happy for it to be moved over to `mediawiki` if that's the way things are done.

**Comment by mwjames** [comment]
> to my tests install via Composer now works as expected.

:+1: 

> but happy for it to be moved over to mediawiki if that's the way things are done.

I think this entirely up to you. Having it under mediawiki/ might improve discoverability but functionality wise it doesn't change anything.

You may want to add your skin to [0] as well, so others can appreciate your work. I added it to [1] since it works on Funtoo Linux wiki (that's where I first discovered your skin) together with SMW.

[0] http://www.mediawiki.org/wiki/Category:All_skins
[1] https://www.semantic-mediawiki.org/wiki/Help:Skins

**Comment by mwjames** [comment]
One think I couldn't find was a license.

**Comment by andru** [comment]
Good call. I've added a license file, and created pages on MediaWiki for this skin and for the Skinny extension which it needs to work.  Thanks for the nudge, I've been meaning to get some of this stuff sorted for a long time :)

**Comment by mwjames** [comment]
Seems to be solved therefore closing it. Cheers
